version: 2
updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - ruby
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - javascript
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
