blank_issues_enabled: false
contact_links:
  - name: Report a security issue
    url: https://www.konversio.org
    about: Please report security vulnerabilities here rather than opening a public issue.
  - name: Product Documentation
    url: https://www.konversio.org
    about: If you have questions or want to understand the product better, please check out our documentation.
