export const KONVERSIO_SET_USER = 'KONVERSIO_SET_USER';
export const KONVERSIO_RESET = 'KONVERSIO_RESET';

export const ANALYTICS_IDENTITY = 'ANALYTICS_IDENTITY';
export const ANALYTICS_RESET = 'ANALYTICS_RESET';
